### ISSUE TITLE
Duplicated functions in common and target

### ISSUE THREAD

**Issue by phanrahan** [phanrahan/mantle#84]
There are some cases where we have multiple implementations of a circuit in common and a target directory.

For example, FullAdder is in common and ice40.

Currently, the common implementation takes precedence over the target implementation. It is imported after the target implementation. However, we do cache circuit definitions. So, this may not work at all.

How should we handle this case?

**Comment by leonardt** [comment]
Here's one possibility, add a decorator such as `@weakdefine` which only defines those circuits if they're not already defined.

One mechanism to do this would be to use a `try` block that checks if there's a circuit already defined and excepts the NameError and defines the default (common) implementation.

**Comment by phanrahan** [comment]
That seems like a nice way to do it. 

(I ran into this problem again this morning.)

**Comment by leonardt** [comment]
Took a crack at this with 3c96e6d09c4ebed76d419bda42dc2d06542e94e3

Basically, the decorator approach wouldn't work because by the time we receive the function, it's already been defined (and thus populated the namespace). What I did was implement a weak import function that only imports a name if it hasn't already been defined. https://github.com/phanrahan/mantle/blob/3c96e6d09c4ebed76d419bda42dc2d06542e94e3/mantle/__init__.py#L6-L20

Then, mantle uses this for common
https://github.com/phanrahan/mantle/blob/3c96e6d09c4ebed76d419bda42dc2d06542e94e3/mantle/__init__.py#L47-L48

To test it, I moved the coreir Decode to common, then checked that the mantle40 decode was not overwritten
https://github.com/phanrahan/mantle/blob/72c4f8d70fda5709d987e21a7cbc9b8fab7d5b1e/tests/test_mantle40/test_decode.py#L4-L12

Let me know if this works out for you, it seems brittle so we'll have to be wary and see how far this gets us.
